### ISSUE TITLE
repackage with META 2.0

### ISSUE THREAD

**Issue by miyagawa** [masaki/p5-LWP-UserAgent-DNS-Hosts#1]
this dist brings in a lot of dependencies due to the deps in test_requires. Because this dist uses Module::Install, these are defined as build requirements and cannot be skipped with `cpanm -n`. Please repackage with a modern build tool such as Milla or Minilla.

**Comment by masaki** [comment]
thanks, `minil migrate` and released: https://metacpan.org/release/MASAKI/LWP-UserAgent-DNS-Hosts-0.09

**Comment by miyagawa** [comment]
Thank you!

**Comment by miyagawa** [comment]
Actually, there still is an issue because test modules are defined in `build`. I'll make a PR.
