### ISSUE TITLE
t/11_https.t fails

### ISSUE THREAD

**Issue by eserte** [masaki/p5-LWP-UserAgent-DNS-Hosts#3]
Are you aware of https://rt.cpan.org/Ticket/Display.html?id=119776 ?

**Comment by masaki** [comment]
oh sorry, I confirmed and found Test::Fake::HTTPD issue.

fixed https://github.com/masaki/Test-Fake-HTTPD/commit/45f7f452e64d552860cb5584aa11e4a887e8a925 and released.
if Test-Fake-HTTPD-0.08 is available, we'll update and fix this issue.

**Comment by masaki** [comment]
released 0.11 https://github.com/masaki/p5-LWP-UserAgent-DNS-Hosts/commit/a07d9049a431fb86fbca3e9cf00038d990408947
