### ISSUE TITLE
https.pm - add SSL_hostname in addition to SSL_verifycn_name

### ISSUE THREAD

**Issue by noxxi** [masaki/p5-LWP-UserAgent-DNS-Hosts#4]
To support setups using the SNI TLS extension it is necessary, that not only the target IP address and hostname used for validation are adapted, but that also the hostname used for SNI gets provided. By default this name gets extracted from the PeerAddr/PeerHost configuration but this is not possible if only an IP address is provided. The following code should probably work (not tested):

```
12    if (my $peer_addr = LWP::UserAgent::DNS::Hosts->_registered_peer_addr($host)) {
13        push @opts, (
14            PeerAddr          => $peer_addr,
15            Host              => $host,
16            SSL_verifycn_name => $host,
+             SSL_hostname      => $host,   # for SNI
17        );
18    }
```

See also https://stackoverflow.com/a/43684553/3081018

**Comment by masaki** [comment]
Thanks, and I read https://gitub.com/libwww-perl/LWP-Protocol-https/pull/17

**Comment by masaki** [comment]
released https://metacpan.org/release/MASAKI/LWP-UserAgent-DNS-Hosts-0.12
